### ISSUE TITLE
Ardougne Rooftop

### ISSUE THREAD

**Issue by aekramer** [TicTac7x/runelite-daily#1]
Hi @TicTac7x ,

Sorry to intrude in the wrong repo, but I was unable to find any other way of reaching out or through the proper one.
https://github.com/TicTac7x/runelite-plugins/tree/plugin-rooftops

Anyway, I was wondering if you would like assistance on obtaining information for the Ardougne Rooftop course as I have just unlocked 90 agility myself, I would just need a little bit of guidance with what information you require exactly, is this all obtainable through RuneLite developer mode?

Many thanks for your plugins, I also very much enjoy the Sulliuscep one.

**Comment by TicTac7x** [comment]
Thanks for letting me know that you were not available to contact me trough the correct repo. I allowed issues there now. Please contact me through discord, you can find me from the RuneLite discord - https://runelite.net/discord.

**Comment by aekramer** [comment]
> Thanks for letting me know that you were not available to contact me trough the correct repo. I allowed issues there now. Please contact me through discord, you can find me from the RuneLite discord - https://runelite.net/discord.

Hey, I seem to be unable to join the runelite discord, if you would like you can also add me directly: Alex RuneRealm#1503

**Comment by TicTac7x** [comment]
Added you
